### ISSUE TITLE
Worldgen Upgrade changes how the datapack generates the world

### ISSUE THREAD

**Issue by 22demerathd** [misode/upgrader#16]
[cal45_null_do_not_distribute_1.18.2.zip](https://github.com/misode/upgrader/files/8476900/cal45_null_do_not_distribute_1.18.2.zip)
[cal45_null_do_not_distribute.zip](https://github.com/misode/upgrader/files/8476901/cal45_null_do_not_distribute.zip)

These two generate differently, the 1.18.2 version has no gaps inbetween the islands and no visible void

**Comment by misode** [comment]
Okay I can confirm the difference. This is an issue with how I implemented the noise router upgrading, I have to investigate this.

1.18.1
![image](https://user-images.githubusercontent.com/17352009/163469713-7ef55a18-1222-461e-85aa-b094c0a05081.png)

1.18.2
![image](https://user-images.githubusercontent.com/17352009/163469894-cac95799-e575-4804-b3c1-26c2ca3f750c.png)

**Comment by misode** [comment]
Okay this was tricky to find. The problem is that the [vanilla `overworld/depth` density function](https://github.com/misode/mcmeta/blob/1.18.2-data/data/minecraft/worldgen/density_function/overworld/depth.json) clamps the output of the terrain shaper spline. The offset spline has values as low as -4 in noise settings, while the depth is clamped between -0.81 and 2.5.

The workaround right now is to overwrite that depth density function with correct `min_value` and `max_value` values. This may also need to be done for the other two terrain shaper fields.

In theory this could be verified and corrected for by the upgrader, but I'm not sure if that's worth it so don't wait for it.
